AWSTemplateFormatVersion: 2010-09-09
Description: Browser Emulator

Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: An Amazon EC2 image ID, such as ami-09e67e426f25ce0d7.
    Default: ami-09e67e426f25ce0d7

Resources:
  BrowserInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: "t3.small"
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
      UserData:
        "Fn::Base64":
          !Sub |
          #!/bin/bash
          set -eu -o pipefail
          # Bash options for strict error checking.
          set -o errexit -o errtrace -o pipefail -o nounset
          shopt -s inherit_errexit 2>/dev/null || true

          # Trace all commands.
          set -o xtrace

          apt-get update
          apt -y upgrade
          command -v python3-pip >/dev/null || {
            apt-get install -y python3-pip
            pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz

          }

          if [[ ! -f "/home/ubuntu/openvidu-loadtest" ]]; then
            git clone https://github.com/OpenVidu/openvidu-loadtest.git /home/ubuntu/openvidu-loadtest
          fi

          sudo /home/ubuntu/openvidu-loadtest/browser-emulator/prepare.sh

          echo "Starting browser emulator"
          cd /home/ubuntu/openvidu-loadtest/browser-emulator
          rm package-lock.json || true
          npm install && sudo npm run start > log.log 2> err.log &

          # sending the finish call
          /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource WaitCondition --region ${AWS::Region}

  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    CreationPolicy:
      ResourceSignal:
        Timeout: PT25M
        Count: 1
